version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/php:7.1
      - image: circleci/redis:5.0.3
    steps:
      - run: sudo docker-php-ext-install sysvsem
      - run: git clone https://github.com/mmeyer2k/monorail .
      - restore_cache:
          keys:
            - v1-dep-{{ .Branch }}-
            - v1-dep-master-
            - v1-dep-
      - run: composer --no-interaction --no-scripts --no-ansi --prefer-dist -a install
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - vendor
      - run: php tests/1.push.php
      - run: php tests/2.sleep.php
      - run: php tests/3.pull.php
      - run: php tests/4.test.php